# Generated by Django 2.1 on 2018-08-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
